lang: 'zh_cn'
buttons: 
    - bold
    - italic
    - '|'
    - unorderedlist
    - orderedlist
    - outdent
    - indent
    - '|'
    - image
    - link
    - '|'
    - fontcolor
    - backcolor
    - '|'
    - alignleft
    - aligncenter
    - alignright
    - justify
    - '|'
    - horizontalrule