# encoding: UTF-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

City.delete_all
cities = City.create([{ town: "北京" },
                      { town: "上海" },
                      { town: "重庆" },
                      { town: "天津" },
                      { town: "合肥", admin: "安徽"},
                      { town: "宿州", admin: "安徽"},
                      { town: "淮北", admin: "安徽"},
                      { town: "阜阳", admin: "安徽"},
                      { town: "蚌埠", admin: "安徽"},
                      { town: "淮南", admin: "安徽"},
                      { town: "滁州", admin: "安徽"},
                      { town: "马鞍山", admin: "安徽"},
                      { town: "芜湖", admin: "安徽"},
                      { town: "铜陵", admin: "安徽"},
                      { town: "安庆", admin: "安徽"},
                      { town: "黄山", admin: "安徽"},
                      { town: "六安", admin: "安徽"},
                      { town: "巢湖", admin: "安徽"},
                      { town: "池州", admin: "安徽"},
                      { town: "宣城", admin: "安徽"},
                      { town: "亳州", admin: "安徽"},
                      { town: "界首", admin: "安徽"},
                      { town: "明光", admin: "安徽"},
                      { town: "天长", admin: "安徽"},
                      { town: "桐城", admin: "安徽"},
                      { town: "宁国", admin: "安徽"},
                      { town: "厦门", admin: "福建"},
                      { town: "福州", admin: "福建"},
                      { town: "南平", admin: "福建"},
                      { town: "三明", admin: "福建"},
                      { town: "莆田", admin: "福建"},
                      { town: "泉州", admin: "福建"},
                      { town: "漳州", admin: "福建"},
                      { town: "龙岩", admin: "福建"},
                      { town: "宁德", admin: "福建"},
                      { town: "福清", admin: "福建"},
                      { town: "长乐", admin: "福建"},
                      { town: "邵武", admin: "福建"},
                      { town: "武夷山", admin: "福建"},
                      { town: "建瓯", admin: "福建"},
                      { town: "建阳", admin: "福建"},
                      { town: "永安", admin: "福建"},
                      { town: "石狮", admin: "福建"},
                      { town: "晋江", admin: "福建"},
                      { town: "南安", admin: "福建"},
                      { town: "龙海", admin: "福建"},
                      { town: "漳平", admin: "福建"},
                      { town: "福安", admin: "福建"},
                      { town: "福鼎", admin: "福建"},
                      { town: "兰州", admin: "甘肃"},
                      { town: "嘉峪关", admin: "甘肃"},
                      { town: "金昌", admin: "甘肃"},
                      { town: "白银", admin: "甘肃"},
                      { town: "天水", admin: "甘肃"},
                      { town: "酒泉", admin: "甘肃"},
                      { town: "张掖", admin: "甘肃"},
                      { town: "武威", admin: "甘肃"},
                      { town: "庆阳", admin: "甘肃"},
                      { town: "平凉", admin: "甘肃"},
                      { town: "定西", admin: "甘肃"},
                      { town: "陇南", admin: "甘肃"},
                      { town: "玉门", admin: "甘肃"},
                      { town: "敦煌", admin: "甘肃"},
                      { town: "临夏", admin: "甘肃"},
                      { town: "合作", admin: "甘肃"},
                      { town: " 广州", admin: "广东"},
                      { town: "深圳", admin: "广东"},
                      { town: "清远", admin: "广东"},
                      { town: "韶关", admin: "广东"},
                      { town: "河源", admin: "广东"},
                      { town: "梅州", admin: "广东"},
                      { town: "潮州", admin: "广东"},
                      { town: "汕头", admin: "广东"},
                      { town: "揭阳", admin: "广东"},
                      { town: "汕尾", admin: "广东"},
                      { town: "惠州", admin: "广东"},
                      { town: "东莞", admin: "广东"},
                      { town: "珠海", admin: "广东"},
                      { town: "中山", admin: "广东"},
                      { town: "江门", admin: "广东"},
                      { town: "佛山", admin: "广东"},
                      { town: "肇庆", admin: "广东"},
                      { town: "云浮", admin: "广东"},
                      { town: "阳江", admin: "广东"},
                      { town: "茂名", admin: "广东"},
                      { town: "湛江", admin: "广东"},
                      { town: "从化", admin: "广东"},
                      { town: "增城", admin: "广东"},
                      { town: "英德", admin: "广东"},
                      { town: "连州", admin: "广东"},
                      { town: "乐昌", admin: "广东"},
                      { town: "南雄", admin: "广东"},
                      { town: "兴宁", admin: "广东"},
                      { town: "普宁", admin: "广东"},
                      { town: "陆丰", admin: "广东"},
                      { town: "恩平", admin: "广东"},
                      { town: "台山", admin: "广东"},
                      { town: "开平", admin: "广东"},
                      { town: "鹤山", admin: "广东"},
                      { town: "高要", admin: "广东"},
                      { town: "四会", admin: "广东"},
                      { town: "罗定", admin: "广东"},
                      { town: "阳春", admin: "广东"},
                      { town: "化州", admin: "广东"},
                      { town: "信宜", admin: "广东"},
                      { town: "高州", admin: "广东"},
                      { town: "吴川", admin: "广东"},
                      { town: "廉江", admin: "广东"},
                      { town: "雷州", admin: "广东"},
                      { town: "贵阳", admin: "贵州"},
                      { town: "六盘水", admin: "贵州"},
                      { town: "遵义", admin: "贵州"},
                      { town: "安顺", admin: "贵州"},
                      { town: "清镇", admin: "贵州"},
                      { town: "赤水", admin: "贵州"},
                      { town: "仁怀", admin: "贵州"},
                      { town: "凯里", admin: "贵州"},
                      { town: "都匀", admin: "贵州"},
                      { town: "兴义", admin: "贵州"},
                      { town: "毕节", admin: "贵州"},
                      { town: "铜仁", admin: "贵州"},
                      { town: "福泉", admin: "贵州"},
                      { town: "石家庄", admin: "河北"},
                      { town: "邯郸", admin: "河北"},
                      { town: "唐山", admin: "河北"},
                      { town: "保定", admin: "河北"},
                      { town: "秦皇岛", admin: "河北"},
                      { town: "邢台", admin: "河北"},
                      { town: "张家口", admin: "河北"},
                      { town: "承德", admin: "河北"},
                      { town: "沧州", admin: "河北"},
                      { town: "廊坊", admin: "河北"},
                      { town: "衡水 ", admin: "河北"},
                      { town: "辛集", admin: "河北"},
                      { town: "藁城", admin: "河北"},
                      { town: "晋州", admin: "河北"},
                      { town: "新乐", admin: "河北"},
                      { town: "鹿泉", admin: "河北"},
                      { town: "丰南", admin: "河北"},
                      { town: "遵化", admin: "河北"},
                      { town: "迁安", admin: "河北"},
                      { town: "霸州", admin: "河北"},
                      { town: "三河", admin: "河北"},
                      { town: "定州", admin: "河北"},
                      { town: "涿州", admin: "河北"},
                      { town: "安国", admin: "河北"},
                      { town: "高碑店", admin: "河北"},
                      { town: "泊头", admin: "河北"},
                      { town: "任丘", admin: "河北"},
                      { town: "黄骅", admin: "河北"},
                      { town: "河间", admin: "河北"},
                      { town: "冀州", admin: "河北"},
                      { town: "深州", admin: "河北"},
                      { town: "南宫", admin: "河北"},
                      { town: "沙河", admin: "河北"},
                      { town: "武安", admin: "河北"},
                      { town: "哈尔滨", admin: "黑龙江"},
                      { town: "齐齐哈尔", admin: "黑龙江"},
                      { town: "黑河", admin: "黑龙江"},
                      { town: "大庆", admin: "黑龙江"},
                      { town: "伊春", admin: "黑龙江"},
                      { town: "鹤岗", admin: "黑龙江"},
                      { town: "佳木斯", admin: "黑龙江"},
                      { town: "双鸭山", admin: "黑龙江"},
                      { town: "七台河", admin: "黑龙江"},
                      { town: "鸡西", admin: "黑龙江"},
                      { town: "牡丹江", admin: "黑龙江"},
                      { town: "绥化", admin: "黑龙江"},
                      { town: "双城", admin: "黑龙江"},
                      { town: "尚志", admin: "黑龙江"},
                      { town: "五常", admin: "黑龙江"},
                      { town: "阿城", admin: "黑龙江"},
                      { town: "讷河", admin: "黑龙江"},
                      { town: "北安", admin: "黑龙江"},
                      { town: "五大连池", admin: "黑龙江"},
                      { town: "铁力", admin: "黑龙江"},
                      { town: "同江", admin: "黑龙江"},
                      { town: "富锦", admin: "黑龙江"},
                      { town: "虎林", admin: "黑龙江"},
                      { town: "密山", admin: "黑龙江"},
                      { town: "绥芬河", admin: "黑龙江"},
                      { town: "海林", admin: "黑龙江"},
                      { town: "宁安", admin: "黑龙江"},
                      { town: "安达", admin: "黑龙江"},
                      { town: "肇东", admin: "黑龙江"},
                      { town: "海伦", admin: "黑龙江"},
                      { town: "郑州", admin: "河南"},
                      { town: "开封", admin: "河南"},
                      { town: "洛阳", admin: "河南"},
                      { town: "平顶山", admin: "河南"},
                      { town: "安阳", admin: "河南"},
                      { town: "鹤壁", admin: "河南"},
                      { town: "新乡", admin: "河南"},
                      { town: "焦作", admin: "河南"},
                      { town: "濮阳", admin: "河南"},
                      { town: "许昌", admin: "河南"},
                      { town: "漯河", admin: "河南"},
                      { town: "三门峡", admin: "河南"},
                      { town: "南阳", admin: "河南"},
                      { town: "商丘", admin: "河南"},
                      { town: "周口", admin: "河南"},
                      { town: "驻马店", admin: "河南"},
                      { town: "信阳", admin: "河南"},
                      { town: "济源", admin: "河南"},
                      { town: "荥阳", admin: "河南"},
                      { town: "新郑", admin: "河南"},
                      { town: "登封", admin: "河南"},
                      { town: "新密", admin: "河南"},
                      { town: "巩义", admin: "河南"},
                      { town: "邓州", admin: "河南"},
                      { town: "偃师", admin: "河南"},
                      { town: "孟州", admin: "河南"},
                      { town: "沁阳", admin: "河南"},
                      { town: "卫辉", admin: "河南"},
                      { town: "辉县", admin: "河南"},
                      { town: "林州", admin: "河南"},
                      { town: "永城", admin: "河南"},
                      { town: "禹州", admin: "河南"},
                      { town: "长葛", admin: "河南"},
                      { town: "舞钢", admin: "河南"},
                      { town: "汝州", admin: "河南"},
                      { town: "义马", admin: "河南"},
                      { town: "灵宝", admin: "河南"},
                      { town: "项城", admin: "河南"},
                      { town: "武汉", admin: "湖北"},
                      { town: "十堰", admin: "湖北"},
                      { town: "襄樊", admin: "湖北"},
                      { town: "荆门", admin: "湖北"},
                      { town: "孝感", admin: "湖北"},
                      { town: "黄冈", admin: "湖北"},
                      { town: "鄂州", admin: "湖北"},
                      { town: "黄石", admin: "湖北"},
                      { town: "咸宁", admin: "湖北"},
                      { town: "荆州", admin: "湖北"},
                      { town: "宜昌", admin: "湖北"},
                      { town: "随州", admin: "湖北"},
                      { town: "仙桃", admin: "湖北"},
                      { town: "天门", admin: "湖北"},
                      { town: "潜江", admin: "湖北"},
                      { town: "丹江口", admin: "湖北"},
                      { town: "老河口", admin: "湖北"},
                      { town: "枣阳", admin: "湖北"},
                      { town: "宜城", admin: "湖北"},
                      { town: "钟祥", admin: "湖北"},
                      { town: "汉川", admin: "湖北"},
                      { town: "应城", admin: "湖北"},
                      { town: "安陆", admin: "湖北"},
                      { town: "广水", admin: "湖北"},
                      { town: "麻城", admin: "湖北"},
                      { town: "武穴", admin: "湖北"},
                      { town: "大冶", admin: "湖北"},
                      { town: "赤壁", admin: "湖北"},
                      { town: "石首", admin: "湖北"},
                      { town: "洪湖", admin: "湖北"},
                      { town: "松滋", admin: "湖北"},
                      { town: "宜都", admin: "湖北"},
                      { town: "枝江", admin: "湖北"},
                      { town: "当阳", admin: "湖北"},
                      { town: "恩施", admin: "湖北"},
                      { town: "利川", admin: "湖北"},
                      { town: "长沙", admin: "湖南"},
                      { town: "张家界", admin: "湖南"},
                      { town: "常德", admin: "湖南"},
                      { town: "益阳", admin: "湖南"},
                      { town: "岳阳", admin: "湖南"},
                      { town: "株洲", admin: "湖南"},
                      { town: "湘潭", admin: "湖南"},
                      { town: "衡阳", admin: "湖南"},
                      { town: "郴州", admin: "湖南"},
                      { town: "永州", admin: "湖南"},
                      { town: "邵阳", admin: "湖南"},
                      { town: "怀化", admin: "湖南"},
                      { town: "娄底", admin: "湖南"},
                      { town: "浏阳", admin: "湖南"},
                      { town: "津市", admin: "湖南"},
                      { town: "沅江", admin: "湖南"},
                      { town: "汨罗", admin: "湖南"},
                      { town: "临湘", admin: "湖南"},
                      { town: "醴陵", admin: "湖南"},
                      { town: "湘乡", admin: "湖南"},
                      { town: "韶山", admin: "湖南"},
                      { town: "耒阳", admin: "湖南"},
                      { town: "常宁", admin: "湖南"},
                      { town: "资兴", admin: "湖南"},
                      { town: "武冈", admin: "湖南"},
                      { town: "洪江", admin: "湖南"},
                      { town: "冷水江", admin: "湖南"},
                      { town: "涟源", admin: "湖南"},
                      { town: "吉首", admin: "湖南"},
                      { town: "长春", admin: "吉林"},
                      { town: "吉林市", admin: "吉林"},
                      { town: "白城", admin: "吉林"},
                      { town: "松原", admin: "吉林"},
                      { town: "四平", admin: "吉林"},
                      { town: "辽源", admin: "吉林"},
                      { town: "通化", admin: "吉林"},
                      { town: "白山", admin: "吉林"},
                      { town: "德惠", admin: "吉林"},
                      { town: "九台", admin: "吉林"},
                      { town: "榆树", admin: "吉林"},
                      { town: "磐石", admin: "吉林"},
                      { town: "蛟河", admin: "吉林"},
                      { town: "桦甸", admin: "吉林"},
                      { town: "舒兰", admin: "吉林"},
                      { town: "洮南", admin: "吉林"},
                      { town: "大安", admin: "吉林"},
                      { town: "双辽", admin: "吉林"},
                      { town: "公主岭", admin: "吉林"},
                      { town: "梅河口", admin: "吉林"},
                      { town: "集安", admin: "吉林"},
                      { town: "临江", admin: "吉林"},
                      { town: "延吉", admin: "吉林"},
                      { town: "图们", admin: "吉林"},
                      { town: "敦化", admin: "吉林"},
                      { town: "珲春", admin: "吉林"},
                      { town: "龙井", admin: "吉林"},
                      { town: "和龙", admin: "吉林"},
                      { town: "南昌", admin: "江西"},
                      { town: "九江", admin: "江西"},
                      { town: "景德镇", admin: "江西"},
                      { town: "鹰潭", admin: "江西"},
                      { town: "新余", admin: "江西"},
                      { town: "萍乡", admin: "江西"},
                      { town: "赣州", admin: "江西"},
                      { town: "上饶", admin: "江西"},
                      { town: "抚州", admin: "江西"},
                      { town: "宜春", admin: "江西"},
                      { town: "吉安", admin: "江西"},
                      { town: "瑞昌", admin: "江西"},
                      { town: "乐平", admin: "江西"},
                      { town: "瑞金", admin: "江西"},
                      { town: "南康", admin: "江西"},
                      { town: "德兴", admin: "江西"},
                      { town: "丰城", admin: "江西"},
                      { town: "樟树", admin: "江西"},
                      { town: "高安", admin: "江西"},
                      { town: "井冈山", admin: "江西"},
                      { town: "贵溪", admin: "江西"},
                      { town: "南京", admin: "江苏"},
                      { town: "徐州", admin: "江苏"},
                      { town: "连云港", admin: "江苏"},
                      { town: "宿迁", admin: "江苏"},
                      { town: "淮安", admin: "江苏"},
                      { town: "盐城", admin: "江苏"},
                      { town: "扬州", admin: "江苏"},
                      { town: "泰州", admin: "江苏"},
                      { town: "南通", admin: "江苏"},
                      { town: "镇江", admin: "江苏"},
                      { town: "常州", admin: "江苏"},
                      { town: "无锡", admin: "江苏"},
                      { town: "苏州", admin: "江苏"},
                      { town: "江阴", admin: "江苏"},
                      { town: "宜兴", admin: "江苏"},
                      { town: "邳州", admin: "江苏"},
                      { town: "新沂", admin: "江苏"},
                      { town: "金坛", admin: "江苏"},
                      { town: "溧阳", admin: "江苏"},
                      { town: "常熟", admin: "江苏"},
                      { town: "张家港", admin: "江苏"},
                      { town: "太仓", admin: "江苏"},
                      { town: "昆山", admin: "江苏"},
                      { town: "吴江", admin: "江苏"},
                      { town: "如皋", admin: "江苏"},
                      { town: "通州", admin: "江苏"},
                      { town: "海门", admin: "江苏"},
                      { town: "启东", admin: "江苏"},
                      { town: "大丰", admin: "江苏"},
                      { town: "东台", admin: "江苏"},
                      { town: "高邮", admin: "江苏"},
                      { town: "仪征", admin: "江苏"},
                      { town: "江都", admin: "江苏"},
                      { town: "扬中", admin: "江苏"},
                      { town: "句容", admin: "江苏"},
                      { town: "丹阳", admin: "江苏"},
                      { town: "兴化", admin: "江苏"},
                      { town: "姜堰", admin: "江苏"},
                      { town: "泰兴", admin: "江苏"},
                      { town: "靖江", admin: "江苏"},
                      { town: "沈阳", admin: "辽宁"},
                      { town: "大连", admin: "辽宁"},
                      { town: "朝阳", admin: "辽宁"},
                      { town: "阜新", admin: "辽宁"},
                      { town: "铁岭", admin: "辽宁"},
                      { town: "抚顺", admin: "辽宁"},
                      { town: "本溪", admin: "辽宁"},
                      { town: "辽阳", admin: "辽宁"},
                      { town: "鞍山", admin: "辽宁"},
                      { town: "丹东", admin: "辽宁"},
                      { town: "营口", admin: "辽宁"},
                      { town: "盘锦", admin: "辽宁"},
                      { town: "锦州", admin: "辽宁"},
                      { town: "葫芦岛", admin: "辽宁"},
                      { town: "新民", admin: "辽宁"},
                      { town: "瓦房店", admin: "辽宁"},
                      { town: "普兰店", admin: "辽宁"},
                      { town: "庄河", admin: "辽宁"},
                      { town: "北票", admin: "辽宁"},
                      { town: "凌源", admin: "辽宁"},
                      { town: "调兵山", admin: "辽宁"},
                      { town: "开原", admin: "辽宁"},
                      { town: "灯塔", admin: "辽宁"},
                      { town: "海城", admin: "辽宁"},
                      { town: "凤城", admin: "辽宁"},
                      { town: "东港", admin: "辽宁"},
                      { town: "大石桥", admin: "辽宁"},
                      { town: "盖州", admin: "辽宁"},
                      { town: "凌海", admin: "辽宁"},
                      { town: "北宁", admin: "辽宁"},
                      { town: "兴城", admin: "辽宁"},
                      { town: " 济南", admin: "山东"},
                      { town: "青岛", admin: "山东"},
                      { town: "聊城", admin: "山东"},
                      { town: "德州", admin: "山东"},
                      { town: "东营", admin: "山东"},
                      { town: "淄博", admin: "山东"},
                      { town: "潍坊", admin: "山东"},
                      { town: "烟台", admin: "山东"},
                      { town: "威海", admin: "山东"},
                      { town: "日照", admin: "山东"},
                      { town: "临沂", admin: "山东"},
                      { town: "枣庄", admin: "山东"},
                      { town: "济宁", admin: "山东"},
                      { town: "泰安", admin: "山东"},
                      { town: "莱芜", admin: "山东"},
                      { town: "滨州", admin: "山东"},
                      { town: "菏泽", admin: "山东"},
                      { town: "章丘", admin: "山东"},
                      { town: "胶州", admin: "山东"},
                      { town: "胶南", admin: "山东"},
                      { town: "即墨", admin: "山东"},
                      { town: "平度", admin: "山东"},
                      { town: "莱西", admin: "山东"},
                      { town: "临清", admin: "山东"},
                      { town: "乐陵", admin: "山东"},
                      { town: "禹城", admin: "山东"},
                      { town: "安丘", admin: "山东"},
                      { town: "昌邑", admin: "山东"},
                      { town: "高密", admin: "山东"},
                      { town: "青州", admin: "山东"},
                      { town: "诸城", admin: "山东"},
                      { town: "寿光", admin: "山东"},
                      { town: "栖霞", admin: "山东"},
                      { town: "海阳", admin: "山东"},
                      { town: "龙口", admin: "山东"},
                      { town: "莱阳", admin: "山东"},
                      { town: "莱州", admin: "山东"},
                      { town: "蓬莱", admin: "山东"},
                      { town: "招远", admin: "山东"},
                      { town: "文登", admin: "山东"},
                      { town: "荣成", admin: "山东"},
                      { town: "乳山", admin: "山东"},
                      { town: "滕州", admin: "山东"},
                      { town: "曲阜", admin: "山东"},
                      { town: "兖州", admin: "山东"},
                      { town: "邹城", admin: "山东"},
                      { town: "新泰", admin: "山东"},
                      { town: "肥城", admin: "山东"},
                      { town: "西安", admin: "陕西"},
                      { town: "延安", admin: "陕西"},
                      { town: "铜川", admin: "陕西"},
                      { town: "渭南", admin: "陕西"},
                      { town: "咸阳", admin: "陕西"},
                      { town: "宝鸡", admin: "陕西"},
                      { town: "汉中", admin: "陕西"},
                      { town: "榆林", admin: "陕西"},
                      { town: "商洛", admin: "陕西"},
                      { town: "安康", admin: "陕西"},
                      { town: "韩城", admin: "陕西"},
                      { town: "华阴", admin: "陕西"},
                      { town: "兴平", admin: "陕西"},
                      { town: "太原", admin: "山西"},
                      { town: "大同", admin: "山西"},
                      { town: "朔州", admin: "山西"},
                      { town: "阳泉", admin: "山西"},
                      { town: "长治", admin: "山西"},
                      { town: "晋城", admin: "山西"},
                      { town: "忻州", admin: "山西"},
                      { town: "吕梁", admin: "山西"},
                      { town: "晋中", admin: "山西"},
                      { town: "临汾", admin: "山西"},
                      { town: "运城", admin: "山西"},
                      { town: "古交", admin: "山西"},
                      { town: "潞城", admin: "山西"},
                      { town: "高平", admin: "山西"},
                      { town: "原平", admin: "山西"},
                      { town: "孝义", admin: "山西"},
                      { town: "汾阳", admin: "山西"},
                      { town: "介休", admin: "山西"},
                      { town: "侯马", admin: "山西"},
                      { town: "霍州", admin: "山西"},
                      { town: "永济", admin: "山西"},
                      { town: "河津", admin: "山西"},
                      { town: " 成都 ", admin: "四川"},
                      { town: "广元", admin: "四川"},
                      { town: "绵阳", admin: "四川"},
                      { town: "德阳", admin: "四川"},
                      { town: "南充", admin: "四川"},
                      { town: "广安", admin: "四川"},
                      { town: "遂宁", admin: "四川"},
                      { town: "内江", admin: "四川"},
                      { town: "乐山", admin: "四川"},
                      { town: "自贡", admin: "四川"},
                      { town: "泸州", admin: "四川"},
                      { town: "宜宾", admin: "四川"},
                      { town: "攀枝花", admin: "四川"},
                      { town: "巴中", admin: "四川"},
                      { town: "达州", admin: "四川"},
                      { town: "资阳", admin: "四川"},
                      { town: "眉山", admin: "四川"},
                      { town: "雅安 ", admin: "四川"},
                      { town: "崇州", admin: "四川"},
                      { town: "邛崃", admin: "四川"},
                      { town: "都江堰", admin: "四川"},
                      { town: "彭州", admin: "四川"},
                      { town: "江油", admin: "四川"},
                      { town: "什邡", admin: "四川"},
                      { town: "广汉", admin: "四川"},
                      { town: "绵竹", admin: "四川"},
                      { town: "阆中", admin: "四川"},
                      { town: "华蓥", admin: "四川"},
                      { town: "峨眉山", admin: "四川"},
                      { town: "万源", admin: "四川"},
                      { town: "简阳", admin: "四川"},
                      { town: "西昌", admin: "四川"},
                      { town: "昆明", admin: "云南"},
                      { town: "曲靖", admin: "云南"},
                      { town: "玉溪", admin: "云南"},
                      { town: "丽江", admin: "云南"},
                      { town: "昭通", admin: "云南"},
                      { town: "思茅", admin: "云南"},
                      { town: "临沧", admin: "云南"},
                      { town: "保山", admin: "云南"},
                      { town: "安宁", admin: "云南"},
                      { town: "宣威", admin: "云南"},
                      { town: "潞西", admin: "云南"},
                      { town: "瑞丽", admin: "云南"},
                      { town: "大理", admin: "云南"},
                      { town: "楚雄", admin: "云南"},
                      { town: "个旧", admin: "云南"},
                      { town: "开远", admin: "云南"},
                      { town: "景洪", admin: "云南"},
                      { town: "杭州", admin: "浙江"},
                      { town: "宁波 ", admin: "浙江"},
                      { town: "湖州", admin: "浙江"},
                      { town: "嘉兴", admin: "浙江"},
                      { town: "舟山", admin: "浙江"},
                      { town: "绍兴", admin: "浙江"},
                      { town: "衢州", admin: "浙江"},
                      { town: "金华", admin: "浙江"},
                      { town: "台州", admin: "浙江"},
                      { town: "温州", admin: "浙江"},
                      { town: "丽水", admin: "浙江"},
                      { town: "临安", admin: "浙江"},
                      { town: "富阳", admin: "浙江"},
                      { town: "建德", admin: "浙江"},
                      { town: "慈溪", admin: "浙江"},
                      { town: "余姚", admin: "浙江"},
                      { town: "奉化", admin: "浙江"},
                      { town: "平湖", admin: "浙江"},
                      { town: "海宁", admin: "浙江"},
                      { town: "桐乡", admin: "浙江"},
                      { town: "诸暨", admin: "浙江"},
                      { town: "上虞", admin: "浙江"},
                      { town: "嵊州", admin: "浙江"},
                      { town: "江山", admin: "浙江"},
                      { town: "兰溪", admin: "浙江"},
                      { town: "永康", admin: "浙江"},
                      { town: "义乌", admin: "浙江"},
                      { town: "东阳", admin: "浙江"},
                      { town: "临海", admin: "浙江"},
                      { town: "温岭", admin: "浙江"},
                      { town: "瑞安", admin: "浙江"},
                      { town: "乐清", admin: "浙江"},
                      { town: "龙泉", admin: "浙江"},
                      { town: "西宁", admin: "青海"},
                      { town: "格尔木", admin: "青海"},
                      { town: "德令哈", admin: "青海"},
                      { town: "南宁", admin: "广西"},
                      { town: "桂林", admin: "广西"},
                      { town: "柳州", admin: "广西"},
                      { town: "梧州", admin: "广西"},
                      { town: "贵港", admin: "广西"},
                      { town: "玉林", admin: "广西"},
                      { town: "钦州", admin: "广西"},
                      { town: "北海", admin: "广西"},
                      { town: "防城港", admin: "广西"},
                      { town: "崇左", admin: "广西"},
                      { town: "百色", admin: "广西"},
                      { town: "河池", admin: "广西"},
                      { town: "来宾", admin: "广西"},
                      { town: "贺州", admin: "广西"},
                      { town: "岑溪", admin: "广西"},
                      { town: "桂平", admin: "广西"},
                      { town: "北流", admin: "广西"},
                      { town: "东兴", admin: "广西"},
                      { town: "凭祥", admin: "广西"},
                      { town: "宜州", admin: "广西"},
                      { town: "合山", admin: "广西"},
                      { town: "呼和浩特", admin: "内蒙古"},
                      { town: "包头", admin: "内蒙古"},
                      { town: "乌海", admin: "内蒙古"},
                      { town: "赤峰", admin: "内蒙古"},
                      { town: "呼伦贝尔", admin: "内蒙古"},
                      { town: "通辽", admin: "内蒙古"},
                      { town: "乌兰察布", admin: "内蒙古"},
                      { town: "鄂尔多斯", admin: "内蒙古"},
                      { town: "巴彦淖尔", admin: "内蒙古"},
                      { town: "满洲里", admin: "内蒙古"},
                      { town: "扎兰屯", admin: "内蒙古"},
                      { town: "牙克石", admin: "内蒙古"},
                      { town: "根河", admin: "内蒙古"},
                      { town: "额尔古纳", admin: "内蒙古"},
                      { town: "乌兰浩特", admin: "内蒙古"},
                      { town: "阿尔山", admin: "内蒙古"},
                      { town: "霍林郭勒", admin: "内蒙古"},
                      { town: "锡林浩特", admin: "内蒙古"},
                      { town: "二连浩特", admin: "内蒙古"},
                      { town: "丰镇", admin: "内蒙古"},
                      { town: "银川", admin: "宁夏"},
                      { town: "石嘴山", admin: "宁夏"},
                      { town: "吴忠", admin: "宁夏"},
                      { town: "中卫", admin: "宁夏"},
                      { town: "固原", admin: "宁夏"},
                      { town: "灵武", admin: "宁夏"},
                      { town: "青铜峡", admin: "宁夏"},
                      { town: "拉萨", admin: "西藏"},
                      { town: "日喀则", admin: "西藏"},
                      { town: "乌鲁木齐", admin: "新疆"},
                      { town: "克拉玛依", admin: "新疆"},
                      { town: " 石河子", admin: "新疆"},
                      { town: "阿拉尔", admin: "新疆"},
                      { town: "图木舒克", admin: "新疆"},
                      { town: "五家渠", admin: "新疆"},
                      { town: "喀什", admin: "新疆"},
                      { town: "阿克苏", admin: "新疆"},
                      { town: "和田", admin: "新疆"},
                      { town: "吐鲁番", admin: "新疆"},
                      { town: "哈密", admin: "新疆"},
                      { town: "阿图什", admin: "新疆"},
                      { town: "博乐", admin: "新疆"},
                      { town: "昌吉", admin: "新疆"},
                      { town: "阜康", admin: "新疆"},
                      { town: "米泉", admin: "新疆"},
                      { town: "库尔勒", admin: "新疆"},
                      { town: "伊宁", admin: "新疆"},
                      { town: "奎屯", admin: "新疆"},
                      { town: "塔城", admin: "新疆"},
                      { town: "乌苏", admin: "新疆"},
                      { town: "阿勒泰", admin: "新疆"},
                      { town: "纽约市", admin: "纽约州", country: "美国"},
                      { town: "洛杉矶", admin: "加利福尼亚州", country: "美国"},
                      { town: "芝加哥", admin: "伊利诺州", country: "美国"},
                      { town: "休士顿", admin: "德克萨斯州", country: "美国"},
                      { town: "凤凰城", admin: "亚利桑那州", country: "美国"},
                      { town: "费城", admin: "宾夕法尼亚州", country: "美国"},
                      { town: "圣安东尼奥", admin: "德克萨斯州", country: "美国"},
                      { town: "圣地牙哥", admin: "加利福尼亚州", country: "美国"},
                      { town: "达拉斯", admin: "德克萨斯州", country: "美国"},
                      { town: "圣荷西", admin: "加利福尼亚州", country: "美国"},
                      { town: "底特律", admin: "密西根州", country: "美国"},
                      { town: "杰克逊维尔", admin: "佛罗里达州", country: "美国"},
                      { town: "印第安纳波利斯", admin: "印地安纳州", country: "美国"},
                      { town: "旧金山", admin: "加利福尼亚州", country: "美国"},
                      { town: "哥伦布", admin: "俄亥俄州", country: "美国"},
                      { town: "奥斯汀", admin: "德克萨斯州", country: "美国"},
                      { town: "孟菲斯", admin: "田纳西州", country: "美国"},
                      { town: "福和市", admin: "德克萨斯州", country: "美国"},
                      { town: "巴尔的摩", admin: "马里兰州", country: "美国"},
                      { town: "夏洛特", admin: "北卡罗莱纳州", country: "美国"},
                      { town: "厄尔巴索", admin: "德克萨斯州", country: "美国"},
                      { town: "密尔沃基", admin: "威斯康辛州", country: "美国"},
                      { town: "波士顿", admin: "麻萨诸塞州", country: "美国"},
                      { town: "西雅图", admin: "华盛顿州", country: "美国"},
                      { town: "华盛顿", admin: "哥伦比亚特区", country: "美国"},
                      { town: "丹佛", admin: "科罗拉多州", country: "美国"},
                      { town: "路易维尔", admin: "肯塔基州", country: "美国"},
                      { town: "拉斯维加斯", admin: "内华达州", country: "美国"},
                      { town: "纳什维尔", admin: "田纳西州", country: "美国"},
                      { town: "奥克拉荷马市", admin: "奥克拉荷马州", country: "美国"},
                      { town: "波特兰", admin: "俄勒冈州", country: "美国"},
                      { town: "图森", admin: "亚利桑那州", country: "美国"},
                      { town: "阿布奎基", admin: "新墨西哥州", country: "美国"},
                      { town: "亚特兰大", admin: "乔治亚州", country: "美国"},
                      { town: "长滩", admin: "加利福尼亚州", country: "美国"},
                      { town: "弗雷斯诺", admin: "加利福尼亚州", country: "美国"},
                      { town: "萨克拉门托", admin: "加利福尼亚州", country: "美国"},
                      { town: "梅萨", admin: "亚利桑那州", country: "美国"},
                      { town: "堪萨斯城", admin: "密苏里州", country: "美国"},
                      { town: "克里夫兰", admin: "俄亥俄州", country: "美国"},
                      { town: "维吉尼亚比奇", admin: "维吉尼亚州", country: "美国"},
                      { town: "奥马哈", admin: "内布拉斯加州", country: "美国"},
                      { town: "迈阿密", admin: "佛罗里达州", country: "美国"},
                      { town: "奥克兰", admin: "加利福尼亚州", country: "美国"},
                      { town: "图尔萨", admin: "奥克拉荷马州", country: "美国"},
                      { town: "檀香山", admin: "夏威夷州", country: "美国"},
                      { town: "明尼亚波利斯", admin: "明尼苏达州", country: "美国"},
                      { town: "科罗拉多泉", admin: "科罗拉多州", country: "美国"},
                      { town: "阿灵顿", admin: "德克萨斯州", country: "美国"},
                      { town: "威奇托", admin: "堪萨斯州", country: "美国"},
                      { town: "罗利", admin: "北卡罗莱纳州", country: "美国"},
                      { town: "圣路易斯", admin: "密苏里州", country: "美国"},
                      { town: "圣安娜", admin: "加利福尼亚州", country: "美国"},
                      { town: "安那罕", admin: "加利福尼亚州", country: "美国"},
                      { town: "坦帕", admin: "佛罗里达州", country: "美国"},
                      { town: "辛辛那提", admin: "俄亥俄州", country: "美国"},
                      { town: "匹兹堡", admin: "宾夕法尼亚州", country: "美国"},
                      { town: "贝克斯菲尔德", admin: "加利福尼亚州", country: "美国"},
                      { town: "奥罗拉", admin: "科罗拉多州", country: "美国"},
                      { town: "托莱多", admin: "俄亥俄州", country: "美国"},
                      { town: "里弗塞得", admin: "加利福尼亚州", country: "美国"},
                      { town: "斯托克顿", admin: "加利福尼亚州", country: "美国"},
                      { town: "科珀斯克里斯蒂", admin: "德克萨斯州", country: "美国"},
                      { town: "纽华克", admin: "新泽西州", country: "美国"},
                      { town: "安克雷奇", admin: "阿拉斯加州", country: "美国"},
                      { town: "水牛城", admin: "纽约州", country: "美国"},
                      { town: "圣保罗", admin: "明尼苏达州", country: "美国"},
                      { town: "列克星顿", admin: "肯塔基州", country: "美国"},
                      { town: "普拉诺", admin: "德克萨斯州", country: "美国"},
                      { town: "韦恩堡", admin: "印地安纳州", country: "美国"},
                      { town: "圣彼德斯堡", admin: "佛罗里达州", country: "美国"},
                      { town: "格伦代尔", admin: "亚利桑那州", country: "美国"},
                      { town: "泽西城", admin: "新泽西州", country: "美国"},
                      { town: "林肯", admin: "内布拉斯加州", country: "美国"},
                      { town: "亨德森", admin: "内华达州", country: "美国"},
                      { town: "钱德勒", admin: "亚利桑那州", country: "美国"},
                      { town: "诺福克", admin: "维吉尼亚州", country: "美国"},
                      { town: "格林斯伯勒", admin: "北卡罗来纳州", country: "美国"},
                      { town: "斯科茨代尔", admin: "亚利桑那州", country: "美国"},
                      { town: "巴吞鲁日", admin: "路易斯安那州", country: "美国"},
                      { town: "伯明翰", admin: "阿拉巴马州", country: "美国"},
                      { town: "麦迪逊", admin: "威斯康辛州", country: "美国"},
                      { town: "纽奥良", admin: "路易斯安那州", country: "美国"},
                      { town: "切萨皮克", admin: "维吉尼亚州", country: "美国"},
                      { town: "奥兰多", admin: "佛罗里达州", country: "美国"},
                      { town: "加兰", admin: "德克萨斯州", country: "美国"},
                      { town: "海厄利亚", admin: "佛罗里达州", country: "美国"},
                      { town: "拉雷多", admin: "德克萨斯州", country: "美国"},
                      { town: "丘拉维斯塔", admin: "加利福尼亚州", country: "美国"},
                      { town: "拉伯克", admin: "德克萨斯州", country: "美国"},
                      { town: "雷诺", admin: "内华达州", country: "美国"},
                      { town: "阿克伦", admin: "俄亥俄州", country: "美国"},
                      { town: "德罕", admin: "北卡罗莱纳州", country: "美国"},
                      { town: "罗彻斯特", admin: "纽约州", country: "美国"},
                      { town: "莫德斯托", admin: "加利福尼亚州", country: "美国"},
                      { town: "蒙哥马利", admin: "阿拉巴马州", country: "美国"},
                      { town: "弗里蒙特", admin: "加利福尼亚州", country: "美国"},
                      { town: "什里夫波特", admin: "路易斯安那州", country: "美国"},
                      { town: "阿灵顿", admin: "维吉尼亚州", country: "美国"},
                      { town: "格伦代尔", admin: "加利福尼亚州", country: "美国"},
                      { town: "圣贝纳迪诺", admin: "加利福尼亚州", country: "美国"},
                      { town: "博伊西", admin: "爱达荷州", country: "美国"},
                      { town: "斯波坎", admin: "华盛顿州", country: "美国"},
                      { town: "扬克斯", admin: "纽约州", country: "美国"},
                      { town: "北拉斯维加斯", admin: "内华达州", country: "美国"},
                      { town: "温斯顿-塞勒姆", admin: "北卡罗莱纳州", country: "美国"},
                      { town: "塔科马", admin: "华盛顿州", country: "美国"},
                      { town: "欧文", admin: "德克萨斯州", country: "美国"},
                      { town: "亨丁顿滩", admin: "加利福尼亚州", country: "美国"},
                      { town: "尔湾", admin: "加利福尼亚州", country: "美国"},
                      { town: "德梅因", admin: "爱阿华州", country: "美国"},
                      { town: "大急流城", admin: "密西根州", country: "美国"},
                      { town: "里奇蒙", admin: "维吉尼亚州", country: "美国"},
                      { town: "莫比尔", admin: "阿拉巴马州", country: "美国"},
                      { town: "吉尔伯特", admin: "亚利桑那州", country: "美国"},
                      { town: "奥古斯塔", admin: "乔治亚州", country: "美国"},
                      { town: "哥伦布", admin: "乔治亚州", country: "美国"},
                      { town: "劳德代尔堡", admin: "佛罗里达州", country: "美国"},
                      { town: "阿马里诺", admin: "德克萨斯州", country: "美国"},
                      { town: "奥克斯纳德", admin: "加利福尼亚州", country: "美国"},
                      { town: "小石城", admin: "阿肯色州", country: "美国"},
                      { town: "莫雷诺谷", admin: "加利福尼亚州", country: "美国"},
                      { town: "诺克斯维尔", admin: "田纳西州", country: "美国"},
                      { town: "盐湖城", admin: "犹他州", country: "美国"},
                      { town: "纽波特纽斯", admin: "维吉尼亚州", country: "美国"},
                      { town: "杰克逊", admin: "密西西比州", country: "美国"},
                      { town: "乌斯特", admin: "麻萨诸塞州", country: "美国"},
                      { town: "普洛威顿斯", admin: "罗德岛州", country: "美国"},
                      { town: "安大略", admin: "加利福尼亚州", country: "美国"},
                      { town: "布朗斯维尔", admin: "德克萨斯州", country: "美国"},
                      { town: "库卡蒙格牧场", admin: "加利福尼亚州", country: "美国"},
                      { town: "奥罗拉", admin: "伊利诺州", country: "美国"},
                      { town: "方塔纳", admin: "加利福尼亚州", country: "美国"},
                      { town: "坦佩", admin: "亚利桑那州", country: "美国"},
                      { town: "罗克福德", admin: "伊利诺州", country: "美国"},
                      { town: "亨茨维尔", admin: "阿拉巴马州", country: "美国"},
                      { town: "费页特维", admin: "北卡罗莱纳州", country: "美国"},
                      { town: "圣塔克拉利塔", admin: "加利福尼亚州", country: "美国"},
                      { town: "欧弗兰帕克", admin: "堪萨斯州", country: "美国"},
                      { town: "园林市", admin: "加利福尼亚州", country: "美国"},
                      { town: "欧申赛德", admin: "加利福尼亚州", country: "美国"},
                      { town: "塔拉哈西", admin: "佛罗里达州", country: "美国"},
                      { town: "温哥华", admin: "华盛顿州", country: "美国"},
                      { town: "代顿", admin: "俄亥俄州", country: "美国"},
                      { town: "查塔诺加", admin: "田纳西州", country: "美国"},
                      { town: "波莫纳", admin: "加利福尼亚州", country: "美国"},
                      { town: "圣罗莎", admin: "加利福尼亚州", country: "美国"},
                      { town: "大草原城", admin: "德克萨斯州", country: "美国"},
                      { town: "塞勒姆", admin: "俄勒冈州", country: "美国"},
                      { town: "开普科勒尔", admin: "佛罗里达州", country: "美国"},
                      { town: "斯普林菲尔德", admin: "麻萨诸塞州", country: "美国"},
                      { town: "斯普林菲尔德", admin: "密苏里州", country: "美国"},
                      { town: "科洛纳", admin: "加利福尼亚州", country: "美国"},
                      { town: "潘布鲁克派恩斯", admin: "佛罗里达州", country: "美国"},
                      { town: "帕特森", admin: "新泽西州", country: "美国"},
                      { town: "尤金", admin: "俄勒冈州", country: "美国"},
                      { town: "好莱坞", admin: "佛罗里达州", country: "美国"},
                      { town: "萨利纳斯", admin: "加利福尼亚州", country: "美国"},
                      { town: "汉普顿", admin: "维吉尼亚州", country: "美国"},
                      { town: "帕萨迪纳", admin: "德克萨斯州", country: "美国"},
                      { town: "帕萨迪纳", admin: "加利福尼亚州", country: "美国"},
                      { town: "圣露西港", admin: "佛罗里达州", country: "美国"},
                      { town: "堪萨斯城", admin: "堪萨斯州", country: "美国"},
                      { town: "内珀维尔", admin: "伊利诺州", country: "美国"},
                      { town: "乔利埃特", admin: "伊利诺州", country: "美国"},
                      { town: "苏瀑", admin: "南达科他州", country: "美国"},
                      { town: "托伦斯", admin: "加利福尼亚州", country: "美国"},
                      { town: "皮奥里亚", admin: "亚利桑那州", country: "美国"},
                      { town: "兰开斯特", admin: "加利福尼亚州", country: "美国"},
                      { town: "雪城", admin: "纽约州", country: "美国"},
                      { town: "海沃德", admin: "加利福尼亚州", country: "美国"},
                      { town: "莱克伍德", admin: "科罗拉多州", country: "美国"},
                      { town: "棕榈谷", admin: "加利福尼亚州", country: "美国"},
                      { town: "亚历山德里亚", admin: "维吉尼亚州", country: "美国"},
                      { town: "桥港", admin: "康乃狄克州", country: "美国"},
                      { town: "橙市", admin: "加利福尼亚州", country: "美国"},
                      { town: "沃伦", admin: "密西根州", country: "美国"},
                      { town: "埃斯孔迪多", admin: "加利福尼亚州", country: "美国"},
                      { town: "富勒顿", admin: "加利福尼亚州", country: "美国"},
                      { town: "梅斯基特", admin: "德克萨斯州", country: "美国"},
                      { town: "森尼韦尔", admin: "加利福尼亚州", country: "美国"},
                      { town: "科勒尔斯普林斯", admin: "佛罗里达州", country: "美国"},
                      { town: "科林斯堡", admin: "科罗拉多州", country: "美国"},
                      { town: "埃尔克格罗夫", admin: "加利福尼亚州", country: "美国"},
                      { town: "斯特灵海茨", admin: "密西根州", country: "美国"},
                      { town: "沙瓦纳", admin: "乔治亚州", country: "美国"},
                      { town: "麦卡伦", admin: "德克萨斯州", country: "美国"},
                      { town: "伊丽莎白", admin: "新泽西州", country: "美国"},
                      { town: "哈特福", admin: "康乃狄克州", country: "美国"},
                      { town: "锡达拉皮兹", admin: "爱阿华州", country: "美国"},
                      { town: "千橡市", admin: "加利福尼亚州", country: "美国"},
                      { town: "纽黑文", admin: "康乃狄克州", country: "美国"},
                      { town: "埃尔蒙特", admin: "加利福尼亚州", country: "美国"},
                      { town: "康科德", admin: "加利福尼亚州", country: "美国"},
                      { town: "托皮卡", admin: "堪萨斯州", country: "美国"},
                      { town: "卡罗尔顿", admin: "德克萨斯州", country: "美国"},
                      { town: "韦科", admin: "德克萨斯州", country: "美国"},
                      { town: "西米谷", admin: "加利福尼亚州", country: "美国"},
                      { town: "西瓦利城", admin: "犹他州", country: "美国"},
                      { town: "哥伦比亚", admin: "南卡罗莱纳州", country: "美国"},
                      { town: "斯坦福", admin: "康乃狄克州", country: "美国"},
                      { town: "贝尔维尤", admin: "华盛顿州", country: "美国"},
                      { town: "弗林特", admin: "密西根州", country: "美国"},
                      { town: "瓦列霍", admin: "加利福尼亚州", country: "美国"},
                      { town: "斯普林菲尔德", admin: "伊利诺州", country: "美国"},
                      { town: "埃文斯维尔", admin: "印地安纳州", country: "美国"},
                      { town: "英格尔伍德", admin: "加利福尼亚州", country: "美国"},
                      { town: "阿比林", admin: "德克萨斯州", country: "美国"},
                      { town: "奥拉西", admin: "堪萨斯州", country: "美国"},
                      { town: "兰盛", admin: "密西根州", country: "美国"},
                      { town: "拉法叶", admin: "路易斯安那州", country: "美国"},
                      { town: "普若佛", admin: "犹他州", country: "美国"},
                      { town: "维塞利亚", admin: "加利福尼亚州", country: "美国"},
                      { town: "安娜堡", admin: "密西根州", country: "美国"},
                      { town: "克拉克斯维尔", admin: "田纳西州", country: "美国"},
                      { town: "皮奥里亚", admin: "伊利诺州", country: "美国"},
                      { town: "卡瑞市", admin: "北卡罗莱纳州", country: "美国"},
                      { town: "雅典", admin: "乔治亚州", country: "美国"},
                      { town: "博蒙特", admin: "德克萨斯州", country: "美国"},
                      { town: "科斯塔梅萨", admin: "加利福尼亚州", country: "美国"},
                      { town: "登顿", admin: "德克萨斯州", country: "美国"},
                      { town: "曼彻斯特", admin: "新罕布夏州", country: "美国"},
                      { town: "独立城", admin: "密苏里州", country: "美国"},
                      { town: "唐尼", admin: "加利福尼亚州", country: "美国"},
                      { town: "桑顿", admin: "科罗拉多州", country: "美国"},
                      { town: "盖恩斯维尔", admin: "佛罗里达州", country: "美国"},
                      { town: "圣克拉拉", admin: "加利福尼亚州", country: "美国"},
                      { town: "米拉马尔", admin: "佛罗里达州", country: "美国"},
                      { town: "查尔斯顿", admin: "南卡罗莱纳州", country: "美国"},
                      { town: "西柯汶纳", admin: "加利福尼亚州", country: "美国"},
                      { town: "克利尔沃特", admin: "佛罗里达州", country: "美国"},
                      { town: "麦金尼", admin: "德克萨斯州", country: "美国"},
                      { town: "阿伦敦", admin: "宾夕法尼亚州", country: "美国"},
                      { town: "沃特伯里", admin: "康乃狄克州", country: "美国"},
                      { town: "罗斯维尔", admin: "加利福尼亚州", country: "美国"},
                      { town: "西敏", admin: "科罗拉多州", country: "美国"},
                      { town: "诺沃克", admin: "加利福尼亚州", country: "美国"},
                      { town: "南本德", admin: "印地安纳州", country: "美国"},
                      { town: "费尔菲尔德", admin: "加利福尼亚州", country: "美国"},
                      { town: "阿瓦达", admin: "科罗拉多州", country: "美国"},
                      { town: "庞帕诺比奇", admin: "佛罗里达州", country: "美国"},
                      { town: "伯班克", admin: "加利福尼亚州", country: "美国"},
                      { town: "文图拉", admin: "加利福尼亚州", country: "美国"},
                      { town: "普韦布洛", admin: "科罗拉多州", country: "美国"},
                      { town: "洛厄尔", admin: "麻萨诸塞州", country: "美国"},
                      { town: "诺曼", admin: "奥克拉荷马州", country: "美国"},
                      { town: "里奇蒙", admin: "加利福尼亚州", country: "美国"},
                      { town: "米德兰", admin: "德克萨斯州", country: "美国"},
                      { town: "伊利", admin: "宾夕法尼亚州", country: "美国"},
                      { town: "基林", admin: "德克萨斯州", country: "美国"},
                      { town: "埃尔金", admin: "伊利诺州", country: "美国"},
                      { town: "柏克莱", admin: "加利福尼亚州", country: "美国"},
                      { town: "朴茨茅斯", admin: "维吉尼亚州", country: "美国"},
                      { town: "剑桥", admin: "麻萨诸塞州", country: "美国"},
                      { town: "戴利城", admin: "加利福尼亚州", country: "美国"},
                      { town: "安条克", admin: "加利福尼亚州", country: "美国"},
                      { town: "绿湾", admin: "威斯康辛州", country: "美国"},
                      { town: "西约旦", admin: "犹他州", country: "美国"},
                      { town: "比灵斯", admin: "蒙大拿州", country: "美国"}])
